# Generated by Django 4.1.2 on 2022-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contato", models.CharField(max_length=100, verbose_name="Contato")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=30, verbose_name="Telefone")),
                ("assunto", models.CharField(max_length=100, verbose_name="Assunto")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                ("created_at", models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
